spring.application.name=SwiggyService

spring.datasource.url=jdbc:mysql://localhost:3306/vali
spring.datasource.username=root
spring.datasource.password=Rajib@1994

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type=TRACE
